name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build the toolchain using CMake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache CMake dependencies
        uses: actions/cache@v3
        with:
          key: cmake-deps
          path: ./deps/*-src
      - name: Install GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Unix Makefiles
          options: CMAKE_TOOLCHAIN_FILE=stm32-cmake/stm32/toolchain/gcc.cmake
      - name: Build the project
        run: cmake --build build
